- name: install docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Dowload KinD
  ansible.builtin.command:
    cmd: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
    
- name: Make KinD executable
  ansible.builtin.command:
    cmd: chmod +x ./kind

- name : move to bin folder
  ansible.buildin.command:
    cmd : mv ./kind /usr/local/bin/kind

- name : download kubectl
  ansible.builtin.command:
    cmd: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name : install kubectl
  ansible.builtin.command:
    cmd: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: install helm
  ansible.builtin.package:
    name: helm
    state: present