---
- name: Set up environment with Docker, KinD, kubectl, and Helm
  hosts: all
  become: yes
  tasks:

    - name: Uninstall old Docker versions
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-selinux
          - docker-engine-selinux
          - docker-engine
        state: absent

    - name: Install required packages for Docker
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: present

    - name: Add Docker CE repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg

    - name: Install Docker CE
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install KinD
      ansible.builtin.get_url:
        url: https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: '0755'

    - name: Download and install kubectl
      ansible.builtin.shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Helm
      ansible.builtin.package:
        name: helm
        state: present

    - name: Copy kind-cluster.yaml to remote host
      ansible.builtin.copy:
        src: ansible/kubernetes/kind-cluster.yaml
        dest: /root/ansible-proj/kind-cluster.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Create KinD Cluster
      ansible.builtin.shell: |
        kind create cluster --name Project-KinD --config /root/kind-cluster.yaml
      args:
        creates: /root/.kube/config
